# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['foo']

# %% ../00_core.ipynb 4
def foo(bar: str, foobar: str, extra: str = 'c') -> str:
    """foobars the bar.

    Args:
        bar (str): the bar.
        foobar (str): the foobar.
        extra (str): extra bar.

    Returns:
        str: the foobar.
    """
    return 'foobar'
