# AUTOGENERATED! DO NOT EDIT! File to edit: ../01_preprocesses.ipynb.

# %% auto 0
__all__ = ['Preprocessor']

# %% ../01_preprocesses.ipynb 4
from typing import List, Callable
from nbdev.showdoc import *
from IPython.display import display,SVG
from transformers import AutoFeatureExtractor
from datasets.dataset_dict import DatasetDict
from .datasets import dataloader_pipeline

# %% ../01_preprocesses.ipynb 6
class Preprocessor(object):

    def __init__(self, model_checkpoint: str = "facebook/wav2vec2-base"):
        self.model_checkpoint = model_checkpoint
        self.FEATURE_EXTRACTOR = AutoFeatureExtractor.from_pretrained(model_checkpoint)

    def _preprocess_function(self, examples: List[dict], max_duration: float = 1.0, padding: bool = False):
        """Runs the feature_extractor for the given checkpoint with max_duration.

        Args:
            examples (_type_): Audio example

        Returns:
            _type_: preprocessed example
        """
        audio_arrays = [x["array"] for x in examples["audio"]]
        inputs = self.FEATURE_EXTRACTOR(
            audio_arrays, 
            sampling_rate=self.FEATURE_EXTRACTOR.sampling_rate, 
            max_length=int(self.FEATURE_EXTRACTOR.sampling_rate * max_duration), 
            truncation=True,
            padding=padding
        )
        return inputs

    def preprocess(self, dataset: DatasetDict, fn_kwargs: dict = None):
        return dataset.map(self._preprocess_function, remove_columns=["audio", "file"], batched=True, fn_kwargs=fn_kwargs)

